# Generated by Django 5.0.14 on 2026-09-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baby_glucose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('administration_type', models.CharField(choices=[('drops', 'Drops'), ('measurement', 'Measurement'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drugs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BabyDrugPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_per_day', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_plans', to='baby_glucose.baby')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_plans', to='baby_drugs.drug')),
            ],
            options={
                'ordering': ['baby', 'drug'],
            },
        ),
        migrations.CreateModel(
            name='BabyDrugSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_order', models.PositiveIntegerField()),
                ('scheduled_time', models.TimeField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('baby_drug_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='baby_drugs.babydrugplan')),
            ],
            options={
                'ordering': ['dose_order'],
            },
        ),
        migrations.CreateModel(
            name='DrugTakingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_records', to='baby_drugs.babydrugschedule')),
            ],
            options={
                'ordering': ['-date', 'schedule__dose_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='babydrugschedule',
            constraint=models.UniqueConstraint(fields=('baby_drug_plan', 'dose_order'), name='unique_dose_order_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='babydrugplan',
            constraint=models.UniqueConstraint(fields=('baby', 'drug'), name='unique_drug_per_baby'),
        ),
        migrations.AddConstraint(
            model_name='drugtakingrecord',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='unique_daily_drug_record'),
        ),
    ]
