# Generated by Django 5.0.14 on 2026-09-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrugTakingRecord',
            new_name='DrugIntakeRecord',
        ),
    ]
